.\" $Id$ -*-nroff-*-
.TH FILE_VIEWER 1
.SH NAME
file_viewer \- Display specific part of the file.

.SH SYNOPSIS
.B file_viewer
[-h]
[--help]

.SH DESCRIPTION
.I file_viewer
is display specific part of the file.

.SH OPTIONS
Here is a summary of all the options.
.TP 5
.BI --help
Print (on the standard output) a description of the command line options understood by slim.
.TP 5
.BI -h
Alias for --help

.SH AUTHORS
Keito Ohkubo
