#!/bin/bash

if [ "$1" = "--help" ] || [ $# -eq 0 ] || [ $# -eq 1 ] || [ $# -gt 3 ]; then
	echo 'usage: file_viewer [-h] filename start end'
	echo
	echo 'Display specific part of the file.'
	echo
	echo 'positional arguments:'
	echo '  filename  filename'
	echo '  start     starting line'
	echo '  end       ending line'
	echo
	echo 'optional arguments:'
	echo '  -h, --help show this help message and exit'
	exit 1
fi

if [ -e "$1" ]; then

	CHAR=$(expr "$2" : '\([0-9][0-9]*\)')
	if [ "$2" != "$CHAR" ]; then
		echo "file_viewer: illegal offset -- $2"
		exit 1
	fi

	CHAR=$(expr "$3" : '\([0-9][0-9]*\)')
	if [ "$3" != "$CHAR" ]; then
		echo "file_viewer: illegal offset -- $3"
		exit 1
	fi

	sed -n "$2","$3"p "$1"

else
	echo "$1:No such file"
	exit 1
fi
